source 'https://rubygems.org'
ruby '2.2.3'

gem 'rake'
gem 'ruboty-alias'
gem 'ruboty-aun'
gem 'ruboty-cron'
gem 'ruboty-echo'
gem 'ruboty-google_image'
gem 'ruboty-gengo'
gem 'ruboty-redis'
gem 'ruboty-ruby'
gem 'ruboty-slack'
gem 'ruboty-sudden_death'
gem 'ruboty-yasy'
gem 'ruboty-talk'
gem 'ruboty-train_delay'
gem 'ruboty-twada'
